name: Docker Image CI

on:
  push:
    branches: [ "main" ] # Trigger the workflow on pushes to the main branch

env:
  # Replace with your Docker Hub username
  DOCKER_USERNAME: your-docker-username
  # Replace with your image name (e.g., your-docker-username/my-app)
  IMAGE_NAME: your-docker-username/my-app

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest # Run on the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx, which provides enhanced build capabilities

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Build context is the current directory (where Dockerfile is located)
        push: false # Push the image to the registry
        tags: ${{ env.IMAGE_NAME }}:latest # Tag the image with 'latest'
